[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mercury-monitoring"
license = {file = "LICENSE.txt"}
version = "0.0.2"
authors = [
  { name="Mercury Team", email="mercury.group@bbva.com" },
]
description = "Mercury's monitoring is a library to perform monitoring testing on models and/or datasets.."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
  'matplotlib>=3.0.2',
  'pandas>=0.24.2',
  'scikit-learn>=0.23.1',
  'seaborn',
  'mercury-dataschema',
  'scipy',
  'tensorflow>=1.15',
  'matplotlib>=3.0.2'
]

[project.optional-dependencies]
dev = [
  'pytest',
  'flake8'
]
doc = [
  'mkdocs',
  'mkdocstrings[python]',
  'mkdocs-material',
  'mkdocs-minify-plugin==0.5.0',
  'mkdocs-exclude',
  'nbconvert',
]

[tool.setuptools.packages.find]
include = ["mercury*"]
exclude = ["docs*", "tests*", "tutorials"]


[project.urls]
"Homepage" = "https://github.com/BBVA/mercury-monitoring"
"Bug Tracker" = "https://github.com/BBVA/mercury-monitoring/issues"